-- ============================================================
-- SEED : Données initiales
-- ============================================================

TRUNCATE TABLE categories_abus RESTART IDENTITY CASCADE;
TRUNCATE TABLE pays RESTART IDENTITY CASCADE;

-- Insertion des catégories d'abus (complètes)
INSERT INTO categories_abus (slug, name, icon, color) VALUES
('arrestation-arbitraire', '{"fr":"Arrestation arbitraire","en":"Arbitrary arrest","sw":"Kukamatwa kiholela","lingala":"Kokanga na pamba","tshiluba":"Kukamata mu nji","kikongo":"Kukanga bila ndonga","pt":"Detenção arbitrária","es":"Detención arbitraria"}', 'handcuffs', '#FF6B6B'),
('emeutes', '{"fr":"Émeutes","en":"Riots","sw":"Mapigano","lingala":"Bokanga bato","tshiluba":"Bipumpunu bya bantu","kikongo":"Mbwela ya bantu","pt":"Motins","es":"Disturbios"}', 'fire', '#FFA726'),
('tueries', '{"fr":"Tueries","en":"Killings","sw":"Mauaji","lingala":"Koboma bato","tshiluba":"Kufwa bantu kuingi","kikongo":"Kufwama bantu","pt":"Mortes","es":"Homicidios"}', 'skull', '#D32F2F'),
('presence-militaire-illegale', '{"fr":"Présence militaire illégale","en":"Illegal military presence","sw":"Uwepo wa kijeshi haramu","lingala":"Bato ya mampinga na esika te","tshiluba":"Basoda mu bupesha bu mibi","kikongo":"Basoda ya mbote ve","pt":"Presença militar ilegal","es":"Presencia militar ilegal"}', 'shield-alert', '#1976D2'),
('miliciens', '{"fr":"Miliciens","en":"Militias","sw":"Vikosi vya wanamgambo","lingala":"Bamilisi","tshiluba":"Bamilisi","kikongo":"Bamilisi","pt":"Milícias","es":"Milicianos"}', 'account-group', '#7B1FA2'),
('viol', '{"fr":"Viol","en":"Rape","sw":"Ubakaji","lingala":"Kosalela makasi","tshiluba":"Kukwata mu mibi","kikongo":"Kusombisa muntu mu ngolo","pt":"Estupro","es":"Violación"}', 'alert-octagon', '#C2185B'),
('vol', '{"fr":"Vol","en":"Theft","sw":"Wizi","lingala":"Kokaba","tshiluba":"Kukwata","kikongo":"Kuba","pt":"Roubo","es":"Robo"}', 'bag-personal-off', '#F57C00'),
('agressions', '{"fr":"Agressions","en":"Assaults","sw":"Mashambulizi","lingala":"Kobeta moto","tshiluba":"Kupema bantu","kikongo":"Kukwama bantu","pt":"Agressões","es":"Agresiones"}', 'karate', '#FF9800'),
('enlevement', '{"fr":"Enlèvement","en":"Abduction","sw":"Utekaji","lingala":"Kokanga moto","tshiluba":"Kukwata muntu mu ngolu","kikongo":"Kukanga muntu","pt":"Sequestro","es":"Secuestro"}', 'account-arrow-right', '#0097A7'),
('kidnapping', '{"fr":"Kidnapping","en":"Kidnapping","sw":"Utekaji nyara","lingala":"Kokanga mwana","tshiluba":"Kukwata mwana mu mibi","kikongo":"Kukanga mwana","pt":"Rapto","es":"Secuestro"}', 'baby-buggy', '#00796B'),
('corruption', '{"fr":"Corruption","en":"Corruption","sw":"Ufisadi","lingala":"Kosomba na mbongo","tshiluba":"Kufuluka mu mbongo","kikongo":"Kufumbila mbongo","pt":"Corrupção","es":"Corrupción"}', 'cash-multiple', '#795548'),
('detournement', '{"fr":"Détournement","en":"Embezzlement","sw":"Wizi wa mali ya umma","lingala":"Kokangola mbongo","tshiluba":"Kukumbula bimpe","kikongo":"Kubula mbongo","pt":"Desvio de fundos","es":"Malversación"}', 'cash-sync', '#5D4037'),
('insultes', '{"fr":"Insultes","en":"Insults","sw":"Matusi","lingala":"Kosambwisa","tshiluba":"Kutuka","kikongo":"Kukijila","pt":"Insultos","es":"Insultos"}', 'message-alert', '#E64A19'),
('xenophobie', '{"fr":"Xénophobie","en":"Xenophobia","sw":"Chuki dhidi ya wageni","lingala":"Kobanga bato ya mboka mosusu","tshiluba":"Kutemena bantu ba mboka bimpe","kikongo":"Kukangama na bantu ya mboka mosusu","pt":"Xenofobia","es":"Xenofobia"}', 'account-cancel', '#455A64'),
('racisme', '{"fr":"Racisme","en":"Racism","sw":"Ubaguzi wa rangi","lingala":"Kokabela bato ndenge na rangi","tshiluba":"Kutemena bantu pa buluba","kikongo":"Kubakana bantu na rangi","pt":"Racismo","es":"Racismo"}', 'account-convert', '#263238'),
('tribalisme', '{"fr":"Tribalisme","en":"Tribalism","sw":"Ubaguzi wa kikabila","lingala":"Kokabela bato ndenge na libota","tshiluba":"Kutemena bantu pa bulumbu","kikongo":"Kukonda bantu na makanda","pt":"Tribalismo","es":"Tribalismo"}', 'account-supervisor', '#37474F'),
('espionnage', '{"fr":"Espionnage","en":"Espionage","sw":"Ujasusi","lingala":"Kotalela makambo ya bato","tshiluba":"Kulonda makambo a bantu","kikongo":"Kusoma makambu ya bantu","pt":"Espionagem","es":"Espionaje"}', 'eye', '#004D40'),
('blanchiment-argent', '{"fr":"Blanchiment d''argent","en":"Money laundering","sw":"Kuficha pesa chafu","lingala":"Kokoma mbongo ya mabe na ya malamu","tshiluba":"Kufuluka mbongo mibi","kikongo":"Kusukula mbongo ya mabe","pt":"Lavagem de dinheiro","es":"Blanqueo de dinero"}', 'cash-100', '#2E7D32'),
('financement-terrorisme', '{"fr":"Financement du terrorisme","en":"Terrorism financing","sw":"Kufadhili ugaidi","lingala":"Kopesa mbongo na bato ya terrorisme","tshiluba":"Kupesha mbongo bantu ba mibi","kikongo":"Kufundila basusi","pt":"Financiamento ao terrorismo","es":"Financiación del terrorismo"}', 'terror', '#C62828'),
('proliferation-armes', '{"fr":"Prolifération des armes","en":"Arms proliferation","sw":"Usambazaji wa silaha","lingala":"Kopanza bibundeli mingi","tshiluba":"Kusambila madimbo","kikongo":"Kusakala biseki","pt":"Proliferação de armas","es":"Proliferación de armas"}', 'pistol', '#6A1B9A'),
('braconnage', '{"fr":"Braconnage","en":"Poaching","sw":"Ujangili","lingala":"Koboma banyama ya zamba","tshiluba":"Kusombola banyama","kikongo":"Kukumba banyama ya zamba","pt":"Caça furtiva","es":"Caza furtiva"}', 'deer', '#33691E'),
('proxenetisme', '{"fr":"Proxénétisme","en":"Pimping","sw":"Udalali wa ngono","lingala":"Kokamba bato mpo na nzoto","tshiluba":"Kukwata bantu mu nsombelu","kikongo":"Kusombisa bantu na ngolo","pt":"Proxenetismo","es":"Proxenetismo"}', 'account-wrench', '#880E4F'),
('vente-drogues', '{"fr":"Vente de drogues","en":"Drug selling","sw":"Uuzaji wa dawa za kulevya","lingala":"Koteka biloko ya somo","tshiluba":"Kuteka mampa a fumu","kikongo":"Kusomba bilanga bya mabe","pt":"Venda de drogas","es":"Venta de drogas"}', 'pill', '#4A148C'),
('vente-minerais-illegales', '{"fr":"Vente de minerais illégale","en":"Illegal mineral trade","sw":"Uuzaji haramu wa madini","lingala":"Koteka mabanga ya mabe","tshiluba":"Kuteka mabanga mibi","kikongo":"Kusombisa mabanga ya mabe","pt":"Venda ilegal de minérios","es":"Venta ilegal de minerales"}', 'diamond-stone', '#E65100'),
('autres', '{"fr":"Autres","en":"Others","sw":"Nyingine","lingala":"Mosusu","tshiluba":"Bimpe binene","kikongo":"Biyeka","pt":"Outros","es":"Otros"}', 'dots-horizontal', '#607D8B');

-- Insertion des pays avec leurs indicatifs
INSERT INTO pays (nom, code, indicatif, flag) VALUES
('Afghanistan', 'AF', '+93', '🇦🇫'),
('Afrique du Sud', 'ZA', '+27', '🇿🇦'),
('Albanie', 'AL', '+355', '🇦🇱'),
('Algérie', 'DZ', '+213', '🇩🇿'),
('Allemagne', 'DE', '+49', '🇩🇪'),
('Andorre', 'AD', '+376', '🇦🇩'),
('Angola', 'AO', '+244', '🇦🇴'),
('Antigua-et-Barbuda', 'AG', '+1-268', '🇦🇬'),
('Arabie saoudite', 'SA', '+966', '🇸🇦'),
('Argentine', 'AR', '+54', '🇦🇷'),
('Arménie', 'AM', '+374', '🇦🇲'),
('Australie', 'AU', '+61', '🇦🇺'),
('Autriche', 'AT', '+43', '🇦🇹'),
('Azerbaïdjan', 'AZ', '+994', '🇦🇿'),
('Bahamas', 'BS', '+1-242', '🇧🇸'),
('Bahreïn', 'BH', '+973', '🇧🇭'),
('Bangladesh', 'BD', '+880', '🇧🇩'),
('Barbade', 'BB', '+1-246', '🇧🇧'),
('Belgique', 'BE', '+32', '🇧🇪'),
('Belize', 'BZ', '+501', '🇧🇿'),
('Bénin', 'BJ', '+229', '🇧🇯'),
('Bhoutan', 'BT', '+975', '🇧🇹'),
('Biélorussie', 'BY', '+375', '🇧🇾'),
('Birmanie', 'MM', '+95', '🇲🇲'),
('Bolivie', 'BO', '+591', '🇧🇴'),
('Bosnie-Herzégovine', 'BA', '+387', '🇧🇦'),
('Botswana', 'BW', '+267', '🇧🇼'),
('Brésil', 'BR', '+55', '🇧🇷'),
('Brunei', 'BN', '+673', '🇧🇳'),
('Bulgarie', 'BG', '+359', '🇧🇬'),
('Burkina Faso', 'BF', '+226', '🇧🇫'),
('Burundi', 'BI', '+257', '🇧🇮'),
('Cambodge', 'KH', '+855', '🇰🇭'),
('Cameroun', 'CM', '+237', '🇨🇲'),
('Canada', 'CA', '+1', '🇨🇦'),
('Cap-Vert', 'CV', '+238', '🇨🇻'),
('République centrafricaine', 'CF', '+236', '🇨🇫'),
('Chili', 'CL', '+56', '🇨🇱'),
('Chine', 'CN', '+86', '🇨🇳'),
('Chypre', 'CY', '+357', '🇨🇾'),
('Colombie', 'CO', '+57', '🇨🇴'),
('Comores', 'KM', '+269', '🇰🇲'),
('République du Congo', 'CG', '+242', '🇨🇬'),
('République démocratique du Congo', 'CD', '+243', '🇨🇩'),
('Corée du Nord', 'KP', '+850', '🇰🇵'),
('Corée du Sud', 'KR', '+82', '🇰🇷'),
('Costa Rica', 'CR', '+506', '🇨🇷'),
('Côte d''Ivoire', 'CI', '+225', '🇨🇮'),
('Croatie', 'HR', '+385', '🇭🇷'),
('Cuba', 'CU', '+53', '🇨🇺'),
('Danemark', 'DK', '+45', '🇩🇰'),
('Djibouti', 'DJ', '+253', '🇩🇯'),
('République dominicaine', 'DO', '+1-809', '🇩🇴'),
('Dominique', 'DM', '+1-767', '🇩🇲'),
('Égypte', 'EG', '+20', '🇪🇬'),
('Émirats arabes unis', 'AE', '+971', '🇦🇪'),
('Équateur', 'EC', '+593', '🇪🇨'),
('Érythrée', 'ER', '+291', '🇪🇷'),
('Espagne', 'ES', '+34', '🇪🇸'),
('Estonie', 'EE', '+372', '🇪🇪'),
('Eswatini', 'SZ', '+268', '🇸🇿'),
('États-Unis', 'US', '+1', '🇺🇸'),
('Éthiopie', 'ET', '+251', '🇪🇹'),
('Fidji', 'FJ', '+679', '🇫🇯'),
('Finlande', 'FI', '+358', '🇫🇮'),
('France', 'FR', '+33', '🇫🇷'),
('Gabon', 'GA', '+241', '🇬🇦'),
('Gambie', 'GM', '+220', '🇬🇲'),
('Géorgie', 'GE', '+995', '🇬🇪'),
('Ghana', 'GH', '+233', '🇬🇭'),
('Grèce', 'GR', '+30', '🇬🇷'),
('Grenade', 'GD', '+1-473', '🇬🇩'),
('Guatemala', 'GT', '+502', '🇬🇹'),
('Guinée', 'GN', '+224', '🇬🇳'),
('Guinée-Bissau', 'GW', '+245', '🇬🇼'),
('Guinée équatoriale', 'GQ', '+240', '🇬🇶'),
('Guyana', 'GY', '+592', '🇬🇾'),
('Haïti', 'HT', '+509', '🇭🇹'),
('Honduras', 'HN', '+504', '🇭🇳'),
('Hongrie', 'HU', '+36', '🇭🇺'),
('Îles Marshall', 'MH', '+692', '🇲🇭'),
('Îles Salomon', 'SB', '+677', '🇸🇧'),
('Inde', 'IN', '+91', '🇮🇳'),
('Indonésie', 'ID', '+62', '🇮🇩'),
('Irak', 'IQ', '+964', '🇮🇶'),
('Iran', 'IR', '+98', '🇮🇷'),
('Irlande', 'IE', '+353', '🇮🇪'),
('Islande', 'IS', '+354', '🇮🇸'),
('Israël', 'IL', '+972', '🇮🇱'),
('Italie', 'IT', '+39', '🇮🇹'),
('Jamaïque', 'JM', '+1-876', '🇯🇲'),
('Japon', 'JP', '+81', '🇯🇵'),
('Jordanie', 'JO', '+962', '🇯🇴'),
('Kazakhstan', 'KZ', '+7', '🇰🇿'),
('Kenya', 'KE', '+254', '🇰🇪'),
('Kirghizistan', 'KG', '+996', '🇰🇬'),
('Kiribati', 'KI', '+686', '🇰🇮'),
('Koweït', 'KW', '+965', '🇰🇼'),
('Laos', 'LA', '+856', '🇱🇦'),
('Lesotho', 'LS', '+266', '🇱🇸'),
('Lettonie', 'LV', '+371', '🇱🇻'),
('Liban', 'LB', '+961', '🇱🇧'),
('Libéria', 'LR', '+231', '🇱🇷'),
('Libye', 'LY', '+218', '🇱🇾'),
('Liechtenstein', 'LI', '+423', '🇱🇮'),
('Lituanie', 'LT', '+370', '🇱🇹'),
('Luxembourg', 'LU', '+352', '🇱🇺'),
('Macédoine du Nord', 'MK', '+389', '🇲🇰'),
('Madagascar', 'MG', '+261', '🇲🇬'),
('Malaisie', 'MY', '+60', '🇲🇾'),
('Malawi', 'MW', '+265', '🇲🇼'),
('Maldives', 'MV', '+960', '🇲🇻'),
('Mali', 'ML', '+223', '🇲🇱'),
('Malte', 'MT', '+356', '🇲🇹'),
('Maroc', 'MA', '+212', '🇲🇦'),
('Maurice', 'MU', '+230', '🇲🇺'),
('Mauritanie', 'MR', '+222', '🇲🇷'),
('Mexique', 'MX', '+52', '🇲🇽'),
('Micronésie', 'FM', '+691', '🇫🇲'),
('Moldavie', 'MD', '+373', '🇲🇩'),
('Monaco', 'MC', '+377', '🇲🇨'),
('Mongolie', 'MN', '+976', '🇲🇳'),
('Monténégro', 'ME', '+382', '🇲🇪'),
('Mozambique', 'MZ', '+258', '🇲🇿'),
('Namibie', 'NA', '+264', '🇳🇦'),
('Nauru', 'NR', '+674', '🇳🇷'),
('Népal', 'NP', '+977', '🇳🇵'),
('Nicaragua', 'NI', '+505', '🇳🇮'),
('Niger', 'NE', '+227', '🇳🇪'),
('Nigeria', 'NG', '+234', '🇳🇬'),
('Niue', 'NU', '+683', '🇳🇺'),
('Norvège', 'NO', '+47', '🇳🇴'),
('Nouvelle-Zélande', 'NZ', '+64', '🇳🇿'),
('Oman', 'OM', '+968', '🇴🇲'),
('Ouganda', 'UG', '+256', '🇺🇬'),
('Ouzbékistan', 'UZ', '+998', '🇺🇿'),
('Pakistan', 'PK', '+92', '🇵🇰'),
('Palaos', 'PW', '+680', '🇵🇼'),
('Palestine', 'PS', '+970', '🇵🇸'),
('Panama', 'PA', '+507', '🇵🇦'),
('Papouasie-Nouvelle-Guinée', 'PG', '+675', '🇵🇬'),
('Paraguay', 'PY', '+595', '🇵🇾'),
('Pays-Bas', 'NL', '+31', '🇳🇱'),
('Pérou', 'PE', '+51', '🇵🇪'),
('Philippines', 'PH', '+63', '🇵🇭'),
('Pologne', 'PL', '+48', '🇵🇱'),
('Portugal', 'PT', '+351', '🇵🇹'),
('Qatar', 'QA', '+974', '🇶🇦'),
('Roumanie', 'RO', '+40', '🇷🇴'),
('Royaume-Uni', 'GB', '+44', '🇬🇧'),
('Russie', 'RU', '+7', '🇷🇺'),
('Rwanda', 'RW', '+250', '🇷🇼'),
('Saint-Christophe-et-Niévès', 'KN', '+1-869', '🇰🇳'),
('Sainte-Lucie', 'LC', '+1-758', '🇱🇨'),
('Saint-Marin', 'SM', '+378', '🇸🇲'),
('Saint-Vincent-et-les-Grenadines', 'VC', '+1-784', '🇻🇨'),
('Salvador', 'SV', '+503', '🇸🇻'),
('Samoa', 'WS', '+685', '🇼🇸'),
('Sao Tomé-et-Principe', 'ST', '+239', '🇸🇹'),
('Sénégal', 'SN', '+221', '🇸🇳'),
('Serbie', 'RS', '+381', '🇷🇸'),
('Seychelles', 'SC', '+248', '🇸🇨'),
('Sierra Leone', 'SL', '+232', '🇸🇱'),
('Singapour', 'SG', '+65', '🇸🇬'),
('Slovaquie', 'SK', '+421', '🇸🇰'),
('Slovénie', 'SI', '+386', '🇸🇮'),
('Somalie', 'SO', '+252', '🇸🇴'),
('Soudan', 'SD', '+249', '🇸🇩'),
('Soudan du Sud', 'SS', '+211', '🇸🇸'),
('Sri Lanka', 'LK', '+94', '🇱🇰'),
('Suède', 'SE', '+46', '🇸🇪'),
('Suisse', 'CH', '+41', '🇨🇭'),
('Suriname', 'SR', '+597', '🇸🇷'),
('Syrie', 'SY', '+963', '🇸🇾'),
('Tadjikistan', 'TJ', '+992', '🇹🇯'),
('Tanzanie', 'TZ', '+255', '🇹🇿'),
('Tchad', 'TD', '+235', '🇹🇩'),
('Tchéquie', 'CZ', '+420', '🇨🇿'),
('Thaïlande', 'TH', '+66', '🇹🇭'),
('Timor oriental', 'TL', '+670', '🇹🇱'),
('Togo', 'TG', '+228', '🇹🇬'),
('Tonga', 'TO', '+676', '🇹🇴'),
('Trinité-et-Tobago', 'TT', '+1-868', '🇹🇹'),
('Tunisie', 'TN', '+216', '🇹🇳'),
('Turkménistan', 'TM', '+993', '🇹🇲'),
('Turquie', 'TR', '+90', '🇹🇷'),
('Tuvalu', 'TV', '+688', '🇹🇻'),
('Ukraine', 'UA', '+380', '🇺🇦'),
('Uruguay', 'UY', '+598', '🇺🇾'),
('Vanuatu', 'VU', '+678', '🇻🇺'),
('Vatican', 'VA', '+379', '🇻🇦'),
('Venezuela', 'VE', '+58', '🇻🇪'),
('Vietnam', 'VN', '+84', '🇻🇳'),
('Yémen', 'YE', '+967', '🇾🇪'),
('Zambie', 'ZM', '+260', '🇿🇲'),
('Zimbabwe', 'ZW', '+263', '🇿🇼');

-- Insertion des grandes villes (exemples pour la RDC)
INSERT INTO villes (nom, pays_id, latitude, longitude) VALUES
('Kinshasa', (SELECT id FROM pays WHERE code = 'CD'), -4.4419, 15.2663),
('Lubumbashi', (SELECT id FROM pays WHERE code = 'CD'), -11.6876, 27.5026),
('Mbuji-Mayi', (SELECT id FROM pays WHERE code = 'CD'), -6.1360, 23.5898),
('Kisangani', (SELECT id FROM pays WHERE code = 'CD'), 0.5153, 25.1910),
('Kananga', (SELECT id FROM pays WHERE code = 'CD'), -5.8962, 22.4172);