-- ============================================================
-- SEED : Données initiales - catégories d'abus
-- ============================================================

TRUNCATE TABLE categories_abus RESTART IDENTITY CASCADE;

INSERT INTO categories_abus (slug, name, icon, color) VALUES
('arrestation-arbitraire', '{"fr":"Arrestation arbitraire","en":"Arbitrary arrest","sw":"Kukamatwa kiholela","lingala":"Kokanga na pamba","tshiluba":"Kukamata mu nji","kikongo":"Kukanga bila ndonga","pt":"Detenção arbitrária","es":"Detención arbitraria"}', 'handcuffs', '#FF6B6B'),
('emeutes', '{"fr":"Émeutes","en":"Riots","sw":"Mapigano","lingala":"Bokanga bato","tshiluba":"Bipumpunu bya bantu","kikongo":"Mbwela ya bantu","pt":"Motins","es":"Disturbios"}', 'fire', '#FFA726'),
('tueries', '{"fr":"Tueries","en":"Killings","sw":"Mauaji","lingala":"Koboma bato","tshiluba":"Kufwa bantu kuingi","kikongo":"Kufwama bantu","pt":"Mortes","es":"Homicidios"}', 'skull', '#D32F2F'),
('presence-militaire-illegale', '{"fr":"Présence militaire illégale","en":"Illegal military presence","sw":"Uwepo wa kijeshi haramu","lingala":"Bato ya mampinga na esika te","tshiluba":"Basoda mu bupesha bu mibi","kikongo":"Basoda ya mbote ve","pt":"Presença militar ilegal","es":"Presencia militar ilegal"}', 'shield-alert', '#1976D2'),
('miliciens', '{"fr":"Miliciens","en":"Militias","sw":"Vikosi vya wanamgambo","lingala":"Bamilisi","tshiluba":"Bamilisi","kikongo":"Bamilisi","pt":"Milícias","es":"Milicianos"}', 'account-group', '#7B1FA2'),
('viol', '{"fr":"Viol","en":"Rape","sw":"Ubakaji","lingala":"Kosalela makasi","tshiluba":"Kukwata mu mibi","kikongo":"Kusombisa muntu mu ngolo","pt":"Estupro","es":"Violación"}', 'alert-octagon', '#C2185B'),
('vol', '{"fr":"Vol","en":"Theft","sw":"Wizi","lingala":"Kokaba","tshiluba":"Kukwata","kikongo":"Kuba","pt":"Roubo","es":"Robo"}', 'bag-personal-off', '#F57C00'),
('agressions', '{"fr":"Agressions","en":"Assaults","sw":"Mashambulizi","lingala":"Kobeta moto","tshiluba":"Kupema bantu","kikongo":"Kukwama bantu","pt":"Agressões","es":"Agresiones"}', 'karate', '#FF9800'),
('enlevement', '{"fr":"Enlèvement","en":"Abduction","sw":"Utekaji","lingala":"Kokanga moto","tshiluba":"Kukwata muntu mu ngolu","kikongo":"Kukanga muntu","pt":"Sequestro","es":"Secuestro"}', 'account-arrow-right', '#0097A7'),
('kidnapping', '{"fr":"Kidnapping","en":"Kidnapping","sw":"Utekaji nyara","lingala":"Kokanga mwana","tshiluba":"Kukwata mwana mu mibi","kikongo":"Kukanga mwana","pt":"Rapto","es":"Secuestro"}', 'baby-buggy', '#00796B'),
('corruption', '{"fr":"Corruption","en":"Corruption","sw":"Ufisadi","lingala":"Kosomba na mbongo","tshiluba":"Kufuluka mu mbongo","kikongo":"Kufumbila mbongo","pt":"Corrupção","es":"Corrupción"}', 'cash-multiple', '#795548'),
('detournement', '{"fr":"Détournement","en":"Embezzlement","sw":"Wizi wa mali ya umma","lingala":"Kokangola mbongo","tshiluba":"Kukumbula bimpe","kikongo":"Kubula mbongo","pt":"Desvio de fundos","es":"Malversación"}', 'cash-sync', '#5D4037'),
('insultes', '{"fr":"Insultes","en":"Insults","sw":"Matusi","lingala":"Kosambwisa","tshiluba":"Kutuka","kikongo":"Kukijila","pt":"Insultos","es":"Insultos"}', 'message-alert', '#E64A19'),
('xenophobie', '{"fr":"Xénophobie","en":"Xenophobia","sw":"Chuki dhidi ya wageni","lingala":"Kobanga bato ya mboka mosusu","tshiluba":"Kutemena bantu ba mboka bimpe","kikongo":"Kukangama na bantu ya mboka mosusu","pt":"Xenofobia","es":"Xenofobia"}', 'account-cancel', '#455A64'),
('racisme', '{"fr":"Racisme","en":"Racism","sw":"Ubaguzi wa rangi","lingala":"Kokabela bato ndenge na rangi","tshiluba":"Kutemena bantu pa buluba","kikongo":"Kubakana bantu na rangi","pt":"Racismo","es":"Racismo"}', 'account-convert', '#263238'),
('tribalisme', '{"fr":"Tribalisme","en":"Tribalism","sw":"Ubaguzi wa kikabila","lingala":"Kokabela bato ndenge na libota","tshiluba":"Kutemena bantu pa bulumbu","kikongo":"Kukonda bantu na makanda","pt":"Tribalismo","es":"Tribalismo"}', 'account-supervisor', '#37474F'),
('espionnage', '{"fr":"Espionnage","en":"Espionage","sw":"Ujasusi","lingala":"Kotalela makambo ya bato","tshiluba":"Kulonda makambo a bantu","kikongo":"Kusoma makambu ya bantu","pt":"Espionagem","es":"Espionaje"}', 'eye', '#004D40'),
('blanchiment-argent', '{"fr":"Blanchiment d''argent","en":"Money laundering","sw":"Kuficha pesa chafu","lingala":"Kokoma mbongo ya mabe na ya malamu","tshiluba":"Kufuluka mbongo mibi","kikongo":"Kusukula mbongo ya mabe","pt":"Lavagem de dinheiro","es":"Blanqueo de dinero"}', 'cash-100', '#2E7D32'),
('financement-terrorisme', '{"fr":"Financement du terrorisme","en":"Terrorism financing","sw":"Kufadhili ugaidi","lingala":"Kopesa mbongo na bato ya terrorisme","tshiluba":"Kupesha mbongo bantu ba mibi","kikongo":"Kufundila basusi","pt":"Financiamento ao terrorismo","es":"Financiación del terrorismo"}', 'terror', '#C62828'),
('proliferation-armes', '{"fr":"Prolifération des armes","en":"Arms proliferation","sw":"Usambazaji wa silaha","lingala":"Kopanza bibundeli mingi","tshiluba":"Kusambila madimbo","kikongo":"Kusakala biseki","pt":"Proliferação de armas","es":"Proliferación de armas"}', 'pistol', '#6A1B9A'),
('braconnage', '{"fr":"Braconnage","en":"Poaching","sw":"Ujangili","lingala":"Koboma banyama ya zamba","tshiluba":"Kusombola banyama","kikongo":"Kukumba banyama ya zamba","pt":"Caça furtiva","es":"Caza furtiva"}', 'deer', '#33691E'),
('proxenetisme', '{"fr":"Proxénétisme","en":"Pimping","sw":"Udalali wa ngono","lingala":"Kokamba bato mpo na nzoto","tshiluba":"Kukwata bantu mu nsombelu","kikongo":"Kusombisa bantu na ngolo","pt":"Proxenetismo","es":"Proxenetismo"}', 'account-wrench', '#880E4F'),
('vente-drogues', '{"fr":"Vente de drogues","en":"Drug selling","sw":"Uuzaji wa dawa za kulevya","lingala":"Koteka biloko ya somo","tshiluba":"Kuteka mampa a fumu","kikongo":"Kusomba bilanga bya mabe","pt":"Venda de drogas","es":"Venta de drogas"}', 'pill', '#4A148C'),
('vente-minerais-illegales', '{"fr":"Vente de minerais illégale","en":"Illegal mineral trade","sw":"Uuzaji haramu wa madini","lingala":"Koteka mabanga ya mabe","tshiluba":"Kuteka mabanga mibi","kikongo":"Kusombisa mabanga ya mabe","pt":"Venda ilegal de minérios","es":"Venta ilegal de minerales"}', 'diamond-stone', '#E65100'),
('autres', '{"fr":"Autres","en":"Others","sw":"Nyingine","lingala":"Mosusu","tshiluba":"Bimpe binene","kikongo":"Biyeka","pt":"Outros","es":"Otros"}', 'dots-horizontal', '#607D8B');

-- Insertion des actualités d'exemple (optionnel)
INSERT INTO actualites(titre, description, contenu, categorie, source, url, image_url, date_publication, pays) VALUES
('Nouvelle politique économique en RDC','Le gouvernement annonce de nouvelles mesures économiques pour stimuler la croissance', 'Le gouvernement de la République Démocratique du Congo a dévoilé aujourd''hui un nouveau plan économique visant à stimuler la croissance et à attirer les investissements étrangers. Les mesures incluent des réformes fiscales et des incitations pour les entreprises.', 'politique', 'Radio Okapi', 'https://www.radiookapi.net', 'https://picsum.photos/400/300', NOW() - INTERVAL '1 hour', 'RDC'),
('Victoire des Léopards en match amical','L''équipe nationale de football remporte son match de préparation', 'Les Léopards de la RDC ont remporté une victoire convaincante 3-1 contre l''équipe du Ghana lors d''un match amical de préparation. Les buts ont été marqués par Mbayo, Bakambu et Mputu.', 'sport', 'Fédération de Football RDC', 'https://fecofa-rdc.com', 'https://picsum.photos/400/300', NOW() - INTERVAL '2 hours', 'RDC'),
('Festival culturel à Kinshasa','Grand festival culturel prévu ce weekend au Stade des Martyrs', 'La ville de Kinshasa accueillera ce weekend un grand festival culturel mettant en vedette des artistes locaux et internationaux. L''événement vise à promouvoir la richesse culturelle de la RDC.', 'culture', 'Ministère de la Culture', 'https://culture.gouv.cd', 'https://picsum.photos/400/300', NOW() - INTERVAL '3 hours', 'RDC');